security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: 'auto'
        App\Entity\VermittlerUser: 'auto'

    providers:
        vermittler_users:
            entity:
                class: App\Entity\VermittlerUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            provider: vermittler_users
            user_checker: App\Security\VermittlerAuthenticationChecker
            stateless: true
            json_login:
                check_path: /login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/foo, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
